=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/jsonschema/bindings-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {

        "Context": {
            "$id": "#/definitions/Context",
            "type": "object",
            "title": "The Items Schema",
            "additionalProperties": { "type": "string"}
        },
        "QualifiedName": {
            "$id": "#/definitions/QualifiedName",
            "type": "string",
            "title": "The QualifiedName Schema",
            "default": "",
            "pattern": "^[A-Za-z0-9_]+:(.*)$"
        },
        "XsdType": {
            "$id": "#/definitions/XsdType",
            "type": "string",
            "enum": ["xsd:string", "xsd:int", "xsd:float", "xsd:boolean", "xsd:dateTime"]
        },

        "lang_string": {
            "type": "object",
            "required": [ "@value" ],
            "properties": {
                "@value": {
                    "type": "string"
                },
                "@language": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "ValuesOrIds": {
            "oneOf": [
                {
                    "$ref": "#/definitions/ArrayOfArraysOfValues"
                },
                {
                    "$ref": "#/definitions/ArrayOfIds"
                },
                {
                    "type": "null"
                }
            ]
        },
        "ArrayOfArraysOfValues": {
            "type": "array",
            "items": [
                { "$ref": "#/definitions/ArrayOfValues" }
            ]
        },
        "ArrayOfValues": {
            "$id": "#/definitions/ArrayOfValues",
            "type": "array",
            "items": {
                "anyOf": [
                    { "$ref": "#/definitions/An@value" },
                    { "$ref": "#/definitions/An@id" },
                    { "$ref": "#/definitions/QualifiedName" },
                    { "$ref": "#/definitions/lang_string" }
                ]
            }
        },
        "ArrayOfIds": {
            "$id": "#/definitions/ArrayOfIds",
            "type": "array",
            "items": {
                "anyOf": [
                    { "$ref": "#/definitions/An@id" }
                ]
            }
        },

        "An@id":  {
            "type": "object",
            "properties": {
                "@id": {
                    "type": "string"
                },
                "@type": {"$ref": "#/definitions/XsdType"},

                "@documentation": {
                    "type": "string"
                },
                "@examplar": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                },
                "@input": {
                    "type": "string",
                    "enum": ["compulsory", "optional", "false"]
                },
                "@output": {
                    "type": "string",
                    "enum": ["true", "false"]
                },
                "@sql.table": {
                    "type": "string"
                }
            },
            "required": [
                "@id"
            ],
            "additionalProperties": false
        },
        "An@value": {
            "type": "object",
            "properties": {
                "@value": {
                    "type": "string"
                },
                "@type": {"$ref": "#/definitions/XsdType"},
                "@documentation": {
                    "type": "string"
                },
                "@examplar": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "number"
                        }
                    ]
                },
                "@input" : {
                    "type": "string",
                    "enum": ["compulsory", "optional", "false"]
                },
                "@output" : {
                    "type": "string",
                    "enum": ["true", "false"]
                },
                "@sql.type" : {
                    "type": "string"
                }
            },
            "additionalProperties": false
        }

    },
    "type": "object",
    "properties": {
        "var": {
            "type": "object",
            "patternProperties": {
                "^(?![iI][dD]$)[^:\\[\\]()/\\\\,\\-]+$": { "$ref": "#/definitions/ValuesOrIds" }
            }
        },
        "vargen": {
            "type": "object"
        },
        "context": {
            "$ref": "#/definitions/Context"
        },
        "template": {
            "type":  ["string", "null"]
        },
        "@documentation": {
            "type":  ["string", "null"]
        }
    },
    "required": [
        "var",
        "context"
    ],
    "additionalProperties": false
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/bindings/org/openprovenance/prov/templates/ptm/ptm-expanding.json
{
    "var": {
        "document": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/doc123-456.provn",
                "@documentation": "The document resulting from template expansion",
                "@input": "false",
                "@output": "true",
                "@sql.table": "file"
            }
        ],
        "template": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/template123.provn",
                "@documentation": "The template to be expanded",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "file"
            }
        ],
        "bindings": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/bindings456.json",
                "@documentation": "The bindings used in expansion",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "file"
            }
        ],
        "agent": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "The agent controlling the expansion",
                "@input": "optional"
            }
        ],
        "expanding": [
            {
                "@id": "act:*",
                "@type": "xsd:int",
                "@documentation": "The activity of expanding the template",
                "@output": "true",
                "@sql.table": "activity"
            }
        ],
        "email": [
            [
                {
                    "@value": "mail:*",
                    "@type": "xsd:string",
                    "@documentation": "The agent's email",
                    "@input": "optional"
                }
            ]
        ],
        "time": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformed file is created",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "start": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation starts",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "end": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation ends",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ]
    },
    "context": {
        "ag":  "${PROV_API}/live/agent/",
        "act": "${PROV_API}/live/activity/",
        "file": "${PROV_API}/live/file/"
    },
    "template": "TODO template",
    "@documentation": "TODO doc."
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/cbindings/org/openprovenance/prov/templates/ptm/ptm-instantiating.json
{
    "var": {
        "document": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/doc123-456.provn",
                "@documentation": "The document resulting from template expansion",
                "@input": "false",
                "@output": "true",
                "@sql.table": "file"
            }
        ],
        "provenance": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/prov-doc123-456.prov-csv",
                "@documentation": "The provenance of the document resulting from the template expansion",
                "@input": "false",
                "@output": "true",
                "@sql.table": "file"
            }
        ],
        "template": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/template123.provn",
                "@documentation": "The template to be expanded",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "file"
            }
        ],
        "bindings": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/bindings456.json",
                "@documentation": "The bindings used in expansion",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "file"
            }
        ],
        "agent": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "The agent controlling the expansion",
                "@input": "optional"
            }
        ],
        "instantiating": [
            {
                "@id": "act:*",
                "@type": "xsd:int",
                "@documentation": "The activity of instantiating the template",
                "@output": "true",
                "@sql.table": "activity"
            }
        ],
        "email": [
            [
                {
                    "@value": "mail:*",
                    "@type": "xsd:string",
                    "@examplar": "luc.moreau@kcl.ac.uk",
                    "@documentation": "The agent's email",
                    "@input": "optional"
                }
            ]
        ],
        "time": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformed file is created",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ]
    },
    "context": {
        "ag":  "${PROV_API}/live/agent/",
        "act": "${PROV_API}/live/activity/",
        "file": "${PROV_API}/live/file/"
    },
    "template": "TODO template",
    "@documentation": "TODO doc."
}

=== lucmoreau/ProvToolbox/modules-tutorial/tutorial4/src/main/resources/bindings4.json
{
    "var": {
        "author": [
            {
                "@id": "orcid:0000-0002-3494-120X"
            },
            {
                "@id": "orcid:0000-0003-0183-6910"
            }
        ],
        "name": [
            {
                "@value": "Luc Moreau"
            },
            {
                "@value": "Paul Groth"
            }
        ],
        "quote": [
            {
                "@id": "ex:quote1"
            },
            {
                "@id": "ex:quote2"
            }
        ],
        "value": [
            {
                "@value": "A Little Provenance Goes a Long Way"
            },
            {
                "@value": "... and More Provenance Goes Even Further"
            }
        ],
        "institution": [
            {
                "@id": "ex:inst1"
            },
            {
                "@id": "ex:inst2"
            }
        ]
    },
    "vargen": {},
    "context": {
        "ex": "http://example.org/",
        "tmpl": "http://example.org/tmpl#",
        "prov": "http://www.w3.org/ns/prov#",
        "orcid": "http://orcid.org/"
    },
    "template": null
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/bindings/org/openprovenance/prov/templates/plead/plead-transforming.json
{
    "var": {
        "transformed_file": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "transformed/123.csv",
                "@documentation": "The file resulting from transformation",
                "@input": "false",
                "@output": "true",
                "@sql.table": "file"
            }
        ],
        "file": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/123.csv",
                "@documentation": "The file before transformation",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "file"
            }
        ],
        "organization": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "An organization aiming managing the ML pipeline",
                "@input": "optional"
            }
        ],
        "engineer": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "The engineer developing the ML pipeline",
                "@input": "optional"
            }
        ],
        "transforming": [
            {
                "@id": "act:*",
                "@type": "xsd:int",
                "@documentation": "The activity of transforming the file",
                "@output": "true",
                "@sql.table": "activity"
            }
        ],
        "n_rows": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:int",
                    "@documentation": "The number of rows in the file",
                    "@input": "optional"
                }
            ]
        ],
        "n_cols": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:int",
                    "@documentation": "The number of columns in the file",
                    "@input": "optional"
                }
            ]
        ],
        "path": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:string",
                    "@documentation": "The actual path of the file",
                    "@input": "optional"
                }
            ]
        ],
        "time": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformed file is created",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "start": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation starts",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "end": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation ends",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ]
    },
    "context": {
        "ops": "https://openprovenance.org/sustainability/ns/#",
        "aspect": "${PROV_API}/live/aspect/",
        "impact": "${PROV_API}/live/impact/",
        "ag":  "${PROV_API}/live/agent/",
        "act": "${PROV_API}/live/activity/",
        "file": "${PROV_API}/live/file/"
    },
    "template": "TODO template",
    "@documentation": "TODO doc."
}
