=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/jsonschema/bindings-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {

        "Context": {
            "$id": "#/definitions/Context",
            "type": "object",
            "title": "The Items Schema",
            "additionalProperties": { "type": "string"}
        },
        "QualifiedName": {
            "$id": "#/definitions/QualifiedName",
            "type": "string",
            "title": "The QualifiedName Schema",
            "default": "",
            "pattern": "^[A-Za-z0-9_]+:(.*)$"
        },
        "XsdType": {
            "$id": "#/definitions/XsdType",
            "type": "string",
            "enum": ["xsd:string", "xsd:int", "xsd:float", "xsd:boolean", "xsd:dateTime"]
        },

        "lang_string": {
            "type": "object",
            "required": [ "@value" ],
            "properties": {
                "@value": {
                    "type": "string"
                },
                "@language": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "ValuesOrIds": {
            "oneOf": [
                {
                    "$ref": "#/definitions/ArrayOfArraysOfValues"
                },
                {
                    "$ref": "#/definitions/ArrayOfIds"
                },
                {
                    "type": "null"
                }
            ]
        },
        "ArrayOfArraysOfValues": {
            "type": "array",
            "items": [
                { "$ref": "#/definitions/ArrayOfValues" }
            ]
        },
        "ArrayOfValues": {
            "$id": "#/definitions/ArrayOfValues",
            "type": "array",
            "items": {
                "anyOf": [
                    { "$ref": "#/definitions/An@value" },
                    { "$ref": "#/definitions/An@id" },
                    { "$ref": "#/definitions/QualifiedName" },
                    { "$ref": "#/definitions/lang_string" }
                ]
            }
        },
        "ArrayOfIds": {
            "$id": "#/definitions/ArrayOfIds",
            "type": "array",
            "items": {
                "anyOf": [
                    { "$ref": "#/definitions/An@id" }
                ]
            }
        },

        "An@id":  {
            "type": "object",
            "properties": {
                "@id": {
                    "type": "string"
                },
                "@type": {"$ref": "#/definitions/XsdType"},

                "@documentation": {
                    "type": "string"
                },
                "@examplar": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                },
                "@input": {
                    "type": "string",
                    "enum": ["compulsory", "optional", "false"]
                },
                "@output": {
                    "type": "string",
                    "enum": ["true", "false"]
                },
                "@sql.table": {
                    "type": "string"
                }
            },
            "required": [
                "@id"
            ],
            "additionalProperties": false
        },
        "An@value": {
            "type": "object",
            "properties": {
                "@value": {
                    "type": "string"
                },
                "@type": {"$ref": "#/definitions/XsdType"},
                "@documentation": {
                    "type": "string"
                },
                "@examplar": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "number"
                        }
                    ]
                },
                "@input" : {
                    "type": "string",
                    "enum": ["compulsory", "optional", "false"]
                },
                "@output" : {
                    "type": "string",
                    "enum": ["true", "false"]
                },
                "@sql.type" : {
                    "type": "string"
                }
            },
            "additionalProperties": false
        }

    },
    "type": "object",
    "properties": {
        "var": {
            "type": "object",
            "patternProperties": {
                "^(?![iI][dD]$)[^:\\[\\]()/\\\\,\\-]+$": { "$ref": "#/definitions/ValuesOrIds" }
            }
        },
        "vargen": {
            "type": "object"
        },
        "context": {
            "$ref": "#/definitions/Context"
        },
        "template": {
            "type":  ["string", "null"]
        },
        "@documentation": {
            "type":  ["string", "null"]
        }
    },
    "required": [
        "var",
        "context"
    ],
    "additionalProperties": false
}

=== lucmoreau/ProvToolbox/modules-tutorial/tutorial4/src/main/resources/bindings1.json
{
    "var": {
        "author": [
            {
                "@id": "orcid:0000-0002-3494-120X"
            }
        ],
        "name": [
            {
                "@value": "Luc Moreau"
            }
        ],
        "quote": [
            {
                "@id": "ex:quote1"
            }
        ],
        "value": [
            {
                "@value": "A Little Provenance Goes a Long Way"
            }
        ]
    },
    "vargen": {},
    "context": {
        "ex": "http://example.org/",
        "tmpl": "http://example.org/tmpl#",
        "prov": "http://www.w3.org/ns/prov#",
        "orcid": "http://orcid.org/"
    },
    "template": null
}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/test/resources/bindings/bindings20.json
{
  "var" : {
    "a" : [ {
      "@id" : "ex:av1"
    }, {
      "@id" : "ex:av2"
    }, {
      "@id" : "ex:av3"
    } ],
    "b" : [ {
      "@id" : "ex:bv1"
    }, {
      "@id" : "ex:bv2"
    } ],
    "c" : [ {
      "@id" : "ex:cv1"
    }, {
      "@id" : "ex:cv2"
    } ],
    "d" : [ {
      "@value" : "me1@example"
    }, {
      "@value" : "m22@example"
    } ],
    "e" : [ {
      "@value" : "Luc1@example"
    }, {
      "@value" : "Luc2@example"
    }, {
      "@value" : "Luc3@example"
    }, {
      "@value" : "Luc4@example"
    }, {
      "@value" : "Luc5@example"
    }, [ {
      "@value" : "Luc6@example"
    }, {
      "@value" : "Luc7@example"
    } ] ]
  },
  "vargen" : { },
  "context" : {
    "ex" : "http://example.org/"
  },
  "template" : null
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/bindings/org/openprovenance/prov/templates/plead/plead-validating.json
{
    "var": {
        "score": [
            {
                "@id": "score:*",
                "@type": "xsd:int",
                "@examplar": 232,
                "@documentation": "The result of the validation",
                "@input": "false",
                "@output": "true",
                "@sql.table": "score"
            }
        ],
        "testing_dataset": [
            {
                "@id": "file:*",
                "@type": "xsd:int",
                "@examplar": 123,
                "@documentation": "The dataset used in the validation",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "file"
            }
        ],
        "organization": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "An organization aiming managing the ML pipeline",
                "@input": "optional",
                "@sql.table": "agent"
            }
        ],
        "engineer": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "The engineer developing the ML pipeline",
                "@input": "optional",
                "@sql.table": "agent"
            }
        ],
        "validating": [
            {
                "@id": "act:*",
                "@type": "xsd:int",
                "@documentation": "The activity of validating with the test dataset",
                "@output": "true",
                "@sql.table": "activity"
            }
        ],
        "path": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:string",
                    "@documentation": "The actual path of the file",
                    "@examplar": "/my/path/",
                    "@input": "optional",
                    "@sql.type":  "nullableTEXT"
                }
            ]
        ],
        "score_value": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:double",
                    "@documentation": "The validation score",
                    "@input": "compulsory",
                    "@examplar": 3.1415,
                    "@sql.type": "double precision"
                }
            ]
        ],
        "time": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the pipeline is created",
                    "@input": "optional",
                    "@examplar": "2022-09-01T12:00:01",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "start": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation starts",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "end": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation ends",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ]
    },
    "context": {
        "ag":  "${PROV_API}/live/agent/",
        "act": "${PROV_API}/live/activity/",
        "file": "${PROV_API}/live/file/",
        "score": "${PROV_API}/live/score/"
    },
    "template": "TODO template",
    "@documentation": "TODO doc."
}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/meta/metabindings/product2-2.json
{
    "var" : {
        "start" :                   [{"@id" : "var:start"}],
        "end" :                     [{"@id" : "var:end"}],
        "agent" :                   [{"@id" : "var:agent"}],
        "responsible" :             [{"@id" : "var:responsible"}],
        "input" :                   [{"@id" : "var:input1"},{"@id" : "var:input2"}],
        "path" :                    [{"@id" : "var:path"}],
        "output" :                  [{"@id" : "var:output1"},{"@id" : "var:output2"}],
        "activity" :                [{"@id" : "var:activity"}],

        "agtype" :                  [[{"@id" : "var:agtype"}]],
        "agprops" :                 [[{"@id" : "var:agprops"}]],
        "agprop_values":            [[{"@id" : "var:agprop_values"}]],
        "rtype" :                   [[{"@id" : "var:rtype"}]],
        "rprops" :                  [[{"@id" : "var:rprops"}]],
        "rprop_values":             [[{"@id" : "var:rprop_values"}]],
        "itype" :                   [[{"@id" : "var:itype1"}],        [{"@id" : "var:itype2"}]],
        "ilocation" :               [[{"@id" : "var:ilocation1"}],    [{"@id" : "var:ilocation2"}]],
        "iprops":                   [[{"@id" : "var:iprops1"}],       [{"@id" : "var:iprops2"}]],
        "iprop_values":             [[{"@id" : "var:iprop_values1"}], [{"@id" : "var:iprop_values2"}]],
        "otype" :                   [[{"@id" : "var:otype1"}],        [{"@id" : "var:otype2"}]],
        "olocation" :               [[{"@id" : "var:olocation1"}],    [{"@id" : "var:olocation2"}]],
        "oprops":                   [[{"@id": "var:oprops1"}],        [{"@id" : "var:oprops2"}]],
        "oprop_values":             [[{"@id": "var:oprop_values1"}],  [{"@id" : "var:oprop_values2"}]],
        "atype" :                   [[{"@id" : "var:atype"}]],
        "aprop_values":             [[{"@id": "var:aprop_values"}]]

    },
    "vargen" : {
        "view" : [ {
            "@id" : "vargen:view"
        } ]
    },
    "context" : {
        "plead": "https://plead-project.org/ns/plead#",
        "uuid" : "urn:uuid:",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "var": "http://openprovenance.org/var#",
        "vargen": "http://openprovenance.org/vargen#",
        "prov": "http://www.w3.org/ns/prov#"
    },
    "template" : null
}

=== lucmoreau/ProvToolbox/modules-explanations/prov-explanations/src/test/resources/plead/bindings/old/b1.json
{
    "var" : {
        "institution" : [ {
            "@id" : "ex:institution"
        }],
        "computer": [ {
            "@id": "ex:machine/iMac"
        }],
        "application": [ {
            "@id": "ex:applications/128350251"
        }],
        "application/v1": [ {
            "@id": "ex:applications/v1"
        }],
        "decision": [ {
            "@id": "ex:decision/128350251"
        }],
        "applicant": [ {
            "@id": "ex:applicants/128350251"
        }],
        "credit_history": [ {
            "@id": "ex:credit_history/128350251"
        }],
        "recommendation": [ {
            "@id": "ex:recommendation/128350251"
        }],
        "reviewing": [ {
            "@id": "ex:review_recommendation/128350251"
        }],
        "classifying": [ {
            "@id": "ex:classify_loans/128350251"
        }],
        "fico_score": [ {
            "@id": "ex:fico_score/128350251"
        }],
        "loan_features": [ {
            "@id": "py:loan_features/128350251"
        }],
        "processing": [ {
            "@id": "ex:process_application/128350251"
        }],
        "staff1": [ {
            "@id": "ex:staff/211"
        }],
        "staff2": [ {
            "@id": "ex:staff/112"
        }],
        "credit_agency": [ {
            "@id": "ex:credit_agency"
        }],
        "fico": [ {
            "@id": "ex:fico"
        }],
        "reviewing_request": [ {
            "@id": "ex:review_request/1234"
        }],
        "rectifying": [ {
            "@id": "ex:rectifying/1234"
        }],
        "rectification_review_decision": [ {
            "@id": "ex:rectification_review_decision/1234"
        }],
        "customer_request": [ {
            "@id": "ex:customer_requests/1234"
        }],
        "document": [ {
            "@id": "ex:documents/12754"
        }],
        "pipeline": [ {
            "@id": "py:4780959224"
        }],
        "file": [ {
            "@id": "localfile:dt_pipeline.pickled"
        }]
    },
    "vargen" : { },
    "context" : {
        "pd": "https://pandas.pydata.org/#",
        "py": "urn:python:var:",
        "sk": "https://scikit-learn.org/stable/modules/generated/sklearn.",
        "ln": "https://plead-project.org/ns/loan#",
        "pl": "https://plead-project.org/ns/plead#",
        "localfile": "file:///Users/me/mlpipeline/",
        "ex" : "http://example.org/"
    },
    "template" : null
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/cbindings/org/openprovenance/prov/templates/ptm/ptm-merging.json
{
    "var": {
        "document": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/doc123-456.provn",
                "@documentation": "The document resulting from template merging",
                "@input": "false",
                "@output": "true",
                "@sql.table": "file"
            }
        ],
        "provenance": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/prov-doc123-456.prov-csv",
                "@documentation": "The provenance of the document resulting from the template merging",
                "@input": "false",
                "@output": "true",
                "@sql.table": "file"
            }
        ],
        "template1": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/template123.provn",
                "@documentation": "The first template to be merged",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "file"
            }
        ],
        "template2": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/template345.json",
                "@documentation": "The second template to be merged",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "file"
            }
        ],
        "agent": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "The agent controlling the merge",
                "@input": "optional"
            }
        ],
        "merging": [
            {
                "@id": "act:*",
                "@type": "xsd:int",
                "@documentation": "The activity of merging the templates",
                "@output": "true",
                "@sql.table": "activity"
            }
        ],
        "email": [
            [
                {
                    "@value": "mail:*",
                    "@type": "xsd:string",
                    "@examplar": "luc.moreau@kcl.ac.uk",
                    "@documentation": "The agent's email",
                    "@input": "optional"
                }
            ]
        ],
        "time": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformed file is created",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ]
    },
    "context": {
        "ag":  "${PROV_API}/live/agent/",
        "act": "${PROV_API}/live/activity/",
        "file": "${PROV_API}/live/file/"
    },
    "template": "TODO template",
    "@documentation": "TODO doc."
}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/test/resources/bindings/bindings10.json
{
    "var" : {
        "a" : [ {
            "@id" : "ex:av1"
        } ],
        "d" : [ [{
            "@value" : "me1@example"
        }, {
            "@value" : "m22@example"
        } ]],
        "e" : [ {
            "@id" : "ex:ev1"
        } ],
        "ag" : [ {
            "@id" : "ex:agv1"
        } ],
        "start" : [ {
            "@value" : "2023-09-05T21:31:56.570+01:00",
            "@type" : "xsd:dateTime"
        } ],
        "end" : [ {
            "@value" : "2023-09-05T21:31:56.571+01:00",
            "@type" : "xsd:dateTime"
        } ],
        "pl" : [ {
            "@id" : "ex:pl1"
        } ],
        "e2" : [ {
            "@id" : "ex:ev2"
        } ]
    },
    "vargen" : { },
    "context" : {
        "ex" : "http://example.org/"
    },
    "template" : null
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/bindings/org/openprovenance/prov/templates/plead/plead-training.json
{
    "var": {
        "pipeline": [
            {
                "@id": "file:*",
                "@type": "xsd:int",
                "@examplar": 122,
                "@documentation": "The pipeline resulting from the training",
                "@input": "false",
                "@output": "true",
                "@sql.table": "file"
            }
        ],
        "filename": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:string",
                    "@examplar": "file/123b.csv",
                    "@documentation": "The pipeline filename resulting from the training",
                    "@input": "compulsory",
                    "@output": "false",
                    "@sql.type":  "nonNullableTEXT"
                }
            ]
        ],
        "training_dataset": [
            {
                "@id": "file:*",
                "@type": "xsd:int",
                "@examplar": 121,
                "@documentation": "The dataset used in the training",
                "@input": "compulsory",
                "@sql.table": "file"
            }
        ],
        "organization": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "An organization aiming managing the ML pipeline",
                "@input": "optional",
                "@sql.table": "agent"
            }
        ],
        "engineer": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "The engineer developing the ML pipeline",
                "@input": "optional",
                "@sql.table": "agent"
            }
        ],
        "training": [
            {
                "@id": "act:*",
                "@type": "xsd:int",
                "@documentation": "The activity of transforming the file",
                "@output": "true",
                "@sql.table": "activity"
            }
        ],
        "path": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:string",
                    "@documentation": "The actual path of the file",
                    "@input": "optional",
                    "@sql.type":  "nullableTEXT"
                }
            ]
        ],
        "time": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the pipeline is created",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "start": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation starts",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "end": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation ends",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ]
    },
    "context": {
        "ag":  "${PROV_API}/live/agent/",
        "act": "${PROV_API}/live/activity/",
        "file": "${PROV_API}/live/file/"
    },
    "template": "TODO template",
    "@documentation": "TODO doc."
}
