=== lucmoreau/ProvToolbox/modules-template/prov-template/src/main/resources/jsonschema/bindings-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {

        "Context": {
            "$id": "#/definitions/Context",
            "type": "object",
            "title": "The Items Schema",
            "additionalProperties": { "type": "string"}
        },
        "QualifiedName": {
            "$id": "#/definitions/QualifiedName",
            "type": "string",
            "title": "The QualifiedName Schema",
            "default": "",
            "pattern": "^[A-Za-z0-9_]+:(.*)$"
        },
        "XsdType": {
            "$id": "#/definitions/XsdType",
            "type": "string",
            "enum": ["xsd:string", "xsd:int", "xsd:float", "xsd:boolean", "xsd:dateTime"]
        },

        "lang_string": {
            "type": "object",
            "required": [ "@value" ],
            "properties": {
                "@value": {
                    "type": "string"
                },
                "@language": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "ValuesOrIds": {
            "oneOf": [
                {
                    "$ref": "#/definitions/ArrayOfArraysOfValues"
                },
                {
                    "$ref": "#/definitions/ArrayOfIds"
                },
                {
                    "type": "null"
                }
            ]
        },
        "ArrayOfArraysOfValues": {
            "type": "array",
            "items": [
                { "$ref": "#/definitions/ArrayOfValues" }
            ]
        },
        "ArrayOfValues": {
            "$id": "#/definitions/ArrayOfValues",
            "type": "array",
            "items": {
                "anyOf": [
                    { "$ref": "#/definitions/An@value" },
                    { "$ref": "#/definitions/An@id" },
                    { "$ref": "#/definitions/QualifiedName" },
                    { "$ref": "#/definitions/lang_string" }
                ]
            }
        },
        "ArrayOfIds": {
            "$id": "#/definitions/ArrayOfIds",
            "type": "array",
            "items": {
                "anyOf": [
                    { "$ref": "#/definitions/An@id" }
                ]
            }
        },

        "An@id":  {
            "type": "object",
            "properties": {
                "@id": {
                    "type": "string"
                },
                "@type": {"$ref": "#/definitions/XsdType"},

                "@documentation": {
                    "type": "string"
                },
                "@examplar": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        }
                    ]
                },
                "@input": {
                    "type": "string",
                    "enum": ["compulsory", "optional", "false"]
                },
                "@output": {
                    "type": "string",
                    "enum": ["true", "false"]
                },
                "@sql.table": {
                    "type": "string"
                }
            },
            "required": [
                "@id"
            ],
            "additionalProperties": false
        },
        "An@value": {
            "type": "object",
            "properties": {
                "@value": {
                    "type": "string"
                },
                "@type": {"$ref": "#/definitions/XsdType"},
                "@documentation": {
                    "type": "string"
                },
                "@examplar": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "number"
                        }
                    ]
                },
                "@input" : {
                    "type": "string",
                    "enum": ["compulsory", "optional", "false"]
                },
                "@output" : {
                    "type": "string",
                    "enum": ["true", "false"]
                },
                "@sql.type" : {
                    "type": "string"
                }
            },
            "additionalProperties": false
        }

    },
    "type": "object",
    "properties": {
        "var": {
            "type": "object",
            "patternProperties": {
                "^(?![iI][dD]$)[^:\\[\\]()/\\\\,\\-]+$": { "$ref": "#/definitions/ValuesOrIds" }
            }
        },
        "vargen": {
            "type": "object"
        },
        "context": {
            "$ref": "#/definitions/Context"
        },
        "template": {
            "type":  ["string", "null"]
        },
        "@documentation": {
            "type":  ["string", "null"]
        }
    },
    "required": [
        "var",
        "context"
    ],
    "additionalProperties": false
}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/test/resources/bindings/bindings25a.json
{
  "var" : {
    "a" : [ {
      "@id" : "ex:apple"
    }, {
      "@id" : "ex:orange"
    }, {
      "@id" : "ex:pear"
    } ],
    "b" : [ {
      "@value" : "apple_val"
    }, {
      "@value" : "orange_val"
    }, {
      "@value" : "pear_val"
    } ]
  },
  "vargen" : {
    "a_bundle" : [ {
      "@id" : "uuid:3f43654d-ba81-4a3e-a2aa-c7273ff00219"
    } ]
  },
  "context" : {
    "ex" : "http://example.org/",
    "uuid" : "urn:uuid:"
  },
  "template" : null
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/bindings/org/openprovenance/prov/templates/plead/plead-filtering.json
{
    "var": {
        "filtered_file": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/123b.csv",
                "@documentation": "The file resulting from the filtering",
                "@input": "false",
                "@output": "true",
                "@sql.table": "file"
            }
        ],
        "file": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/123.csv",
                "@documentation": "The file before filtering",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "file"
            }
        ],
        "method": [
            {
                "@id": "method:*",
                "@type": "xsd:string",
                "@examplar": "method/filter.py",
                "@documentation": "The the method to filter the file",
                "@input": "optional",
                "@output": "false",
                "@sql.table": "method"
            }
        ],
        "organization": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "An organization aiming managing the ML pipeline",
                "@input": "optional"
            }
        ],
        "engineer": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "The engineer developing the ML pipeline",
                "@input": "optional"
            }
        ],
        "filtering": [
            {
                "@id": "act:*",
                "@type": "xsd:int",
                "@documentation": "The activity of filtering the file",
                "@output": "true",
                "@sql.table": "activity"
            }
        ],
        "n_rows": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:int",
                    "@documentation": "The number of rows in the file",
                    "@input": "optional"
                }
            ]
        ],
        "n_cols": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:int",
                    "@documentation": "The number of columns in the file",
                    "@input": "optional"
                }
            ]
        ],
        "path": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:string",
                    "@documentation": "The actual path of the file",
                    "@input": "optional"
                }
            ]
        ],
        "time": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the filtered file is created",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "start": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation starts",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "end": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation ends",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ]
    },
    "context": {
        "ag":  "${PROV_API}/live/agent/",
        "act": "${PROV_API}/live/activity/",
        "file": "${PROV_API}/live/file/",
        "method": "${PROV_API}/live/method/"
    },
    "template": "TODO template",
    "@documentation": "TODO doc."
}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/test/resources/bindings/b21.json
{
  "var" : {
    "a" : [ {
      "@id" : "ex:av1"
    }, {
      "@id" : "ex:av2"
    }, {
      "@id" : "ex:av3"
    } ],
    "b" : [ {
      "@id" : "ex:bv1"
    }, {
      "@id" : "ex:bv2"
    } ],
    "c" : [ {
      "@id" : "ex:cv1"
    }, {
      "@id" : "ex:cv2"
    } ],
    "d" : [[ {
      "@value" : "Luc@example"
    }, {
      "@value" : "lm@soton"
    } ]]
  },
  "vargen" : { },
  "context" : {
    "ex" : "http://example.org/"
  },
  "template" : null
}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/test/resources/bindings/a_bindings.json
{
    "var" : {
        "a" : [ {
            "@id" : "ex:a"
        } ],
        "b" : [ {
            "@id" : "ex:b"
        } ],
        "atime" : [ {
            "@value" : "2014-01-01T09:21:00+02:00",
            "@type" : "xsd:dateTime"
        } ],
        "atype" : [ {
            "@id" : "ex:footype_a"
        } ],
        "btype" : [ {
            "@id" : "ex:footype_b"
        } ]
    },
    "vargen" : {
        "bb" : [ {
            "@id" : "uuid:aaa78cf0-be82-4b3c-bccd-af76266dd303"
        } ],
        "d" : [ {
            "@id" : "uuid:5be9652f-2c02-4d59-af57-f848c4b01190"
        } ]
    },
    "context" : {
        "ex" : "http://example.com/",
        "uuid" : "urn:uuid:",
        "xsd": "http://www.w3.org/2001/XMLSchema#"
    },
    "template" : null
}

=== lucmoreau/ProvToolbox/modules-template/prov-template/src/test/resources/bindings/bindings23.json
{
  "var" : {
    "a" : [ {
      "@id" : "ex:av1"
    }, {
      "@id" : "ex:av2"
    }, {
      "@id" : "ex:av3"
    } ],
    "b" : [ {
      "@id" : "ex:bv1"
    }, {
      "@id" : "ex:bv2"
    }, {
      "@id" : "ex:bv3"
    } ],
    "d" : [ {
      "@value" : "me1@example"
    }, {
      "@value" : "me2@example"
    }, {
      "@value" : "me3@example"
    } ],
    "e" : [ {
      "@value" : "Luc1@example"
    }, {
      "@value" : "Luc2@example"
    }, [ {
      "@value" : "Luc6@example"
    }, {
      "@value" : "Luc7@example"
    } ] ],
    "label" : [ {
      "@value" : "label1"
    }, {
      "@value" : "label2"
    }, [ {
      "@value" : "label3"
    }, {
      "@value" : "label3b"
    } ] ]
  },
  "vargen" : {
  },
  "context" : {
    "ex" : "http://example.org/"
  },
  "template" : null
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/bindings/org/openprovenance/prov/templates/plead/plead-approving.json
{
    "var": {

        "approved_pipeline": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/approved-pipeline768",
                "@documentation": "The approved pipeline",
                "@input": "false",
                "@output": "true",
                "@sql.table": "file"
            }
        ],
        "approval_record": [
            {
                "@id": "approval:*",
                "@type": "xsd:int",
                "@examplar": "9885",
                "@documentation": "The approval record",
                "@input": "false",
                "@output": "true"}
        ],
        "pipeline": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/pipeline368",
                "@documentation": "The pipeline before approval",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "file"
            }
        ],
        "score": [
            {
                "@id": "score:*",
                "@type": "xsd:int",
                "@examplar": "356",
                "@documentation": "The score obtained through validation",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "score"
            }
        ],
        "organization": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "An organization aiming managing the ML pipeline",
                "@input": "optional"
            }
        ],
        "manager": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "The manager approving the ML pipeline",
                "@input": "optional"
            }
        ],
        "approving": [
            {
                "@id": "act:*",
                "@type": "xsd:int",
                "@documentation": "The activity of approving the pipeline",
                "@output": "true",
                "@sql.table": "activity"
            }
        ],
        "signature": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:string",
                    "@documentation": "The approval's signature",
                    "@input": "optional"
                }
            ]
        ],
        "path": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:string",
                    "@documentation": "The actual path of the file",
                    "@input": "optional"
                }
            ]
        ],
        "time": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the filtered file is created",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "start": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation starts",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "end": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation ends",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ]
    },
    "context": {
        "ag":  "${PROV_API}/live/agent/",
        "act": "${PROV_API}/live/activity/",
        "file": "${PROV_API}/live/file/",
        "approval": "${PROV_API}/live/approval/"
    },
    "template": "TODO template",
    "@documentation": "TODO doc."
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/bindings/org/openprovenance/prov/templates/plead/plead-splitting.json
{
    "var": {
        "split_file1": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/12378_1.csv",
                "@documentation": "The first file resulting from the split",
                "@input": "false",
                "@output": "true",
                "@sql.table": "file"
            }
        ],
        "split_file2": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/12378_2.csv",
                "@documentation": "The second file resulting from the split",
                "@input": "false",
                "@output": "true",
                "@sql.table": "file"
            }
        ],
        "file": [
            {
                "@id": "file:*",
                "@type": "xsd:string",
                "@examplar": "file/123.csv",
                "@documentation": "The file before transformation",
                "@input": "compulsory",
                "@output": "false",
                "@sql.table": "file"
            }
        ],
        "organization": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "An organization aiming managing the ML pipeline",
                "@input": "optional"
            }
        ],
        "engineer": [
            {
                "@id": "ag:*",
                "@type": "xsd:int",
                "@documentation": "The engineer developing the ML pipeline",
                "@input": "optional"
            }
        ],
        "splitting": [
            {
                "@id": "act:*",
                "@type": "xsd:int",
                "@documentation": "The activity of transforming the file",
                "@output": "true",
                "@sql.table": "activity"
            }
        ],
        "n_rows1": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:int",
                    "@documentation": "The number of rows in the file",
                    "@input": "optional"
                }
            ]
        ],
        "n_cols1": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:int",
                    "@documentation": "The number of columns in the file",
                    "@input": "optional"
                }
            ]
        ],
        "path1": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:string",
                    "@documentation": "The actual path of the file",
                    "@input": "optional"
                }
            ]
        ],
        "n_rows2": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:int",
                    "@documentation": "The number of rows in the file",
                    "@input": "optional"
                }
            ]
        ],
        "n_cols2": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:int",
                    "@documentation": "The number of columns in the file",
                    "@input": "optional"
                }
            ]
        ],
        "path2": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:string",
                    "@documentation": "The actual path of the file",
                    "@input": "optional"
                }
            ]
        ],
        "time": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformed file is created",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "start": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation starts",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ],
        "end": [
            [
                {
                    "@value": "*",
                    "@type": "xsd:dateTime",
                    "@documentation": "Time when the transformation ends",
                    "@input": "optional",
                    "@sql.type":  "timestamptz"
                }
            ]
        ]
    },
    "context": {
        "ag":  "${PROV_API}/live/agent/",
        "act": "${PROV_API}/live/activity/",
        "file": "${PROV_API}/live/file/"
    },
    "template": "TODO template",
    "@documentation": "TODO doc."
}

=== lucmoreau/ProvToolbox/modules-tutorial/tutorial4/src/main/resources/bindings2.json
{
    "var": {
        "author": [
            {
                "@id": "orcid:0000-0002-3494-120X"
            },
            {
                "@id": "orcid:0000-0003-0183-6910"
            }
        ],
        "name": [
            {
                "@value": "Luc Moreau"
            },
            {
                "@value": "Paul Groth"
            }
        ],
        "quote": [
            {
                "@id": "ex:quote1"
            }
        ],
        "value": [
            {
                "@value": "A Little Provenance Goes a Long Way"
            }
        ]
    },
    "vargen": {},
    "context": {
        "ex": "http://example.org/",
        "tmpl": "http://example.org/tmpl#",
        "prov": "http://www.w3.org/ns/prov#",
        "orcid": "http://orcid.org/"
    },
    "template": null
}
