=== lucmoreau/ProvToolbox/modules-template/prov-template-compiler/src/main/resources/schema/template-project-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Project Template Catalogue Schema",
    "definitions": {
        "SimpleTemplateDescriptor": {
            "type": "object",
            "properties": {
                "@type": {
                    "type": "string"
                },
                "fullyQualifiedName": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
                },
                "package": {
                    "type": "string",
                    "pattern": "^(?:([A-Za-z_][A-Za-z0-9_]*)(?:\\.[A-Za-z_][A-Za-z0-9_]*)*|https?:\\/\\/\\S+)$"
                },
                "template": {
                    "type": "string"
                },
                "cbindings": {
                    "type": "string"
                }
            },
            "required": [
                "@type",
                "fullyQualifiedName",
                "name",
                "template",
                "package",
                "cbindings"
            ],
            "additionalProperties": false
        },
        "CompositeTemplateDescriptor": {
            "type": "object",
            "properties": {
                "@type": {
                    "type": "string"
                },
                "fullyQualifiedName": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "package": {
                    "type": "string"
                },
                "consistsOf": {
                    "type": "string"
                },
                "sharing": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "string"
                        }
                    ]
                }
            },
            "required": [
                "@type",
                "fullyQualifiedName",
                "name",
                "package",
                "consistsOf",
                "sharing"
            ],
            "additionalProperties": false
        },
        "TemplateDescriptor": {
            "anyOf": [
                {
                    "$ref": "#/definitions/SimpleTemplateDescriptor"
                },
                {
                    "$ref": "#/definitions/CompositeTemplateDescriptor"
                }
            ]
        },
        "TableDescriptor": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "serial": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "created_at"
            ],
            "additionalProperties": false
        },
        "GeneratorDescriptor": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "class": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object"
                },
                "classpath": {
                    "type": "array",
                    "items": [
                        {
                            "type": "string"
                        }
                    ]
                }
            },
            "required": [
                "class"
            ],
            "additionalProperties": false
        }
    },
    "type": "object",
    "properties": {
        "group": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "destination": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "version": {
            "type": "string"
        },
        "root_package": {
            "type": "string"
        },
        "script": {
            "type": "string"
        },
        "script_dir": {
            "type": "string"
        },
        "python_dir": {
            "type": "string"
        },
        "javascript_dir": {
            "type": "string"
        },
        "rust_dir": {
            "type": "string"
        },
        "integrator": {
            "type": "boolean"
        },
        "jsweet": {
            "type": "boolean"
        },
        "jsonschema": {
            "type": "string"
        },
        "documentation": {
            "type": "string"
        },
        "variableCheck": {
            "type": "string"
        },
        "sqlFile": {
            "type": "string"
        },
        "templates": {
            "type": "array",
            "items": [
                {
                    "$ref": "#/definitions/TemplateDescriptor"
                }
            ]
        },
        "search": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "sql.tables": {
            "type": "object",
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/TableDescriptor"
                }
            }
        },
        "past-generators": {
            "type": "object",
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/GeneratorDescriptor"
                }
            }
        }
    },
    "required": [
        "group",
        "name",
        "destination",
        "description",
        "version",
        "root_package",
        "script",
        "script_dir",
        "jsweet",
        "jsonschema",
        "documentation",

        "templates"
    ],
    "additionalProperties": false
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/config/tp_ptm.json
{
	"group": "org.openprovenance.prov",
	"name": "template_library",
	"destination": "target",
	"description": "PROV templates for prov template management",
	"version": "2.2.3-SNAPSHOT",
	"root_package": "org.openprovenance.prov.template.library.ptm",
	"script": "ptm_run",
	"script_dir": "target/bin",
	"python_dir": "target/generated-python",
	"integrator": true,
	"jsweet": true,
	"jsonschema": "schema-ptm.json",
	"documentation": "doc-ptm.html",
	"sqlFile": "prov-template-library-ptm.sql",
	"templates" : [


		{
			"@type": "simple",
			"name": "ptm_instantiating",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.ptm.PtmInstantiating",
			"template": "org/openprovenance/prov/templates/ptm/ptm-instantiating",
			"package": "org.openprovenance.prov.template.library.ptm",
			"cbindings": "org/openprovenance/prov/templates/ptm/ptm-instantiating.json"
		},

		{
			"@type": "simple",
			"name": "ptm_merging",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.ptm.PtmMerging",
			"template": "org/openprovenance/prov/templates/ptm/ptm-merging",
			"package": "org.openprovenance.prov.template.library.ptm",
			"cbindings": "org/openprovenance/prov/templates/ptm/ptm-merging.json"
		},
		{
			"@type": "simple",
			"name": "ptm_mexpanding",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.ptm.PtmMexpanding",
			"template": "org/openprovenance/prov/templates/ptm/ptm-mexpanding",
			"package": "org.openprovenance.prov.template.library.ptm",
			"cbindings": "org/openprovenance/prov/templates/ptm/ptm-mexpanding.json"
		}

	],
	"sql.tables":  {
		"activity": {
			"id": "SERIAL",
			"created_at": "timestamp with time zone NOT NULL DEFAULT NOW()"
		},
		"file": {
			"id": "SERIAL",
			"created_at": "timestamp with time zone NOT NULL DEFAULT NOW()"
		}

	}
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/config/tp_plead.json
{
    "group": "org.openprovenance.prov",
    "name": "template_library",
    "destination": "target",
    "description": "PROV templates for plead ML pipeline",
    "version": "0.1.0",
    "root_package": "org.openprovenance.prov.template.library.plead",
    "search": ["activity", "file", "agent", "method", "score", "approval_record"],
    "script": "ptm_plead_run",
    "script_dir": "target/bin",
    "python_dir": "target/generated-python",
    "integrator": true,
    "jsweet": true,
    "jsonschema": "schema-plead.json",
    "documentation": "doc-plead.html",
    "sqlFile": "prov-template-library-plead.sql",
    "templates" : [

        {
            "@type": "simple",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.plead.PleadTransforming",
            "name": "plead_transforming",
            "package": "org.openprovenance.prov.template.library.plead",
            "template": "org/openprovenance/prov/templates/plead/plead-transforming",
            "cbindings": "org/openprovenance/prov/templates/plead/plead-transforming.json"
        },

        {
            "@type": "simple",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.plead.PleadFiltering",
            "name": "plead_filtering",
            "package": "org.openprovenance.prov.template.library.plead",
            "template": "org/openprovenance/prov/templates/plead/plead-filtering",
            "cbindings": "org/openprovenance/prov/templates/plead/plead-filtering.json"
        },
        {
            "@type": "simple",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.plead.PleadTraining",
            "name": "plead_training",
            "package": "org.openprovenance.prov.template.library.plead",
            "template": "org/openprovenance/prov/templates/plead/plead-training",
            "cbindings": "org/openprovenance/prov/templates/plead/plead-training.json"
        },
        {
            "@type": "simple",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.plead.PleadValidating",
            "name": "plead_validating",
            "package": "org.openprovenance.prov.template.library.plead",
            "template": "org/openprovenance/prov/templates/plead/plead-validating",
            "cbindings": "org/openprovenance/prov/templates/plead/plead-validating.json"
        },
        {
            "@type": "simple",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.plead.PleadApproving",
            "name": "plead_approving",
            "package": "org.openprovenance.prov.template.library.plead",
            "template": "org/openprovenance/prov/templates/plead/plead-approving",
            "cbindings": "org/openprovenance/prov/templates/plead/plead-approving.json"
        },
        {
            "@type": "simple",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.plead.PleadSplitting",
            "name": "plead_splitting",
            "package": "org.openprovenance.prov.template.library.plead",
            "template": "org/openprovenance/prov/templates/plead/plead-splitting",
            "cbindings": "org/openprovenance/prov/templates/plead/plead-splitting.json"
        },

        {
            "@type": "composite",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.plead.PleadTransformingComposite",
            "name": "plead_transforming_composite",
            "package": "org.openprovenance.prov.template.library.plead",
            "consistsOf": "org.openprovenance.prov.template.library.plead.PleadTransforming",
            "sharing": ["transformed_file", "transforming"]
        }
    ],
    "sql.tables":  {
        "file": {
            "id": "SERIAL",
            "created_at": "timestamp with time zone NOT NULL DEFAULT NOW()"
        },
        "agent": {
            "id": "SERIAL",
            "created_at": "timestamp with time zone NOT NULL DEFAULT NOW()"
        },
        "score": {
            "id": "SERIAL",
            "created_at": "timestamp with time zone NOT NULL DEFAULT NOW()"
        },
        "approval_record": {
            "id": "SERIAL",
            "created_at": "timestamp with time zone NOT NULL DEFAULT NOW()"
        },
        "activity": {
            "id": "SERIAL",
            "created_at": "timestamp with time zone NOT NULL DEFAULT NOW()"
        },
        "method": {
            "id": "SERIAL",
            "serial": "INT",
            "created_at": "timestamp with time zone NOT NULL DEFAULT NOW()"
        }
    }
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-library/src/main/resources/config/tp_pg.json
{
    "group": "org.openprovenance",
    "name": "template_library",
    "destination": "target/",
    "description": "Pokemon Go simulation",
    "version": "0.1.0",
    "root_package": "org.openprovenance.prov.template.library.pg",
    "script": "pokemon_run",
    "script_dir": "target/bin",
    "python_dir": "target/generated-python",
    "integrator": true,
    "jsweet": true,
    "jsonschema": "schema-pg.json",
    "sqlFile": "prov-template-library-pg.sql",
    "documentation": "doc-pg.html",
    "templates" : [

        {
            "@type": "simple",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.pg.PgCapturing",
            "name": "pg_capturing",
            "package": "org.openprovenance.prov.template.library.pg",
            "template": "org/openprovenance/prov/templates/pg/pg-capturing",
            "cbindings": "org/openprovenance/prov/templates/pg/pg-capturing.json"
        },
        {
            "@type": "simple",
            "fullyQualifiedName": "org.openprovenance.prov.template.library.pg.PgBallcollecting",
            "name": "pg_ballcollecting",
            "package": "org.openprovenance.prov.template.library.pg",
            "template": "org/openprovenance/prov/templates/pg/pg-ballcollecting",
            "cbindings": "org/openprovenance/prov/templates/pg/pg-ballcollecting.json"
        }
    ]
}

=== lucmoreau/ProvToolbox/modules-template/prov-template-compiler/src/test/resources/config1.json
{
    "group": "org.example",
    "name": "templates",
    "destination": "target/libs",
    "description": "PROV template demo",
    "version": "0.1.0",
    "script": "example_run",
    "root_package": "org.example.templates.catalogue",
    "script_dir": "target/libs/bin",
    "python_dir": "target/libs/python",
    "jsweet": true,
    "jsonschema": "schema.json",
    "sqlFile": "template.sql",
    "documentation": "doc.html",
    "templates" : [
        {
            "@type": "simple",
            "fullyQualifiedName": "org.example.TemplateBlock",
            "name": "template_block",
            "package": "org.example.templates.block",
            "template": "src/test/resources/templates3/generic_binaryop.provn",
            "cbindings": "src/test/resources/templates3/generic_binaryop_b1.json",
            "interfaces": {
                "plain":  ["java.io.Serializable"],
                "input":  ["java.io.Serializable"],
                "output": ["java.io.Serializable"]
            }
        }
    ]
}
